---
# tasks file for ufw
#
#
- name: Allow all access from RFC1918
  ufw:
    rule: allow
    src: '{{ item }}'
  loop:
    - 10.0.0.0/8
    - 172.16.0.0/12
    - 192.168.0.0/16
  environment:
    PATH: /sbin:{{ ansible_env.PATH }}

